---
- name: create user group
  group: name=wp state=present

- name: add ubuntu to wp
  user: name=ubuntu append=yes groups="adm,wp"

- name: Create www-data user
  user: name={{wp_user}} append=yes groups="adm,wp" shell=/bin/bash

- name: upload sudoers.d file
  copy: src=sudoers-admin dest=/tmp/admin-sudo owner=root group=root mode=0440

- name: move file to sudoers.d
  shell: visudo -q -c -f /tmp/admin-sudo && cp /tmp/admin-sudo /etc/sudoers.d/admin-sudo

- name: install apt requirements
  apt: pkg={{item}} state=present update_cache=yes install_recommends=yes
  with_items:
    - mysql-client-5.5
    - mysql-common
    - php5-common
    - php5-mysql
    - apache2
    - apache2-utils
    - apache2.2-common
    - libapache2-mod-php5
    - python-mysqldb
    - unzip
  notify: restart apache

- name: setup mysql database
  mysql_db: db={{database_name}} state=present login_host={{database_host}} login_password={{database_root_password}} login_user={{database_root_user}}

- name: setup mysql user
  mysql_user: name={{database_user}} password={{database_password}} priv={{database_name}}.*:ALL state=present login_host={{database_host}} login_password={{database_root_password}} login_user={{database_root_user}}

- name: download wordpress
  get_url: url=http://wordpress.org/latest.tar.gz dest={{app_base_dir}}/{{site_name}}.tar.gz mode=0764

- name: untar wordpress
  shell: tar -xzvf {{site_name}}.tar.gz creates=${app_base_dir}/wp-created chdir=${app_base_dir}

- name: create lock file
  file: path=${app_base_dir}/wp-created state=present

#Required for the multisite domain mapping to work
- name: move files from wordpress directory to top level dir
  shell: cp -r {{app_base_dir}}/wordpress/* {{app_base_dir}} chdir={{app_base_dir}}/wordpress creates=${app_base_dir}/wp-moved

- name: create lock file
  file: path=${app_base_dir}/wp-moved state=present

- name: remove wordpress directory
  file: path={{app_base_dir}}/wordpress state=absent

- name: render wp-config.php from template
  template: src=wp-config.php.j2 dest={{app_base_dir}}/wp-config.php owner=root group=root mode=0644

- name: get wordpress domain mapping plugin to enable multiple domains to be used
  get_url: url=http://downloads.wordpress.org/plugin/wordpress-mu-domain-mapping.0.5.4.3.zip dest={{app_base_dir}}/{{mu_plugin_name}}.zip mode=0764

- name: create plugin directory
  file: path={{app_base_dir}}/{{mu_plugin_directory}} state=directory

- name: unzip mu plugin
  shell: unzip ${mu_plugin_name}.zip -u -d ${app_base_dir}/${mu_plugin_directory} chdir=${app_base_dir} creates=${app_base_dir}/mu-plugin-created
  notify: restart apache

- name: create lock file
  file: path=${app_base_dir}/mu-plugin-created state=present

- name: move sunrise.php
  shell: mv {{app_base_dir}}/{{mu_plugin_directory}}/{{mu_plugin_name}}/sunrise.php {{app_base_dir}}/wp-content/sunrise.php

- name: change ownership on files in wordpress directory to wp_user
  shell: chown -R {{wp_user}}:wp {{app_base_dir}}

- name: change ownership on wordpress directory to root
  shell: chown root:root {{app_base_dir}}

- name: create apache directory and set perms
  file: path=/etc/apache2/sites-available owner=root group=edx mode=2775 state=directory

- name: Removing default apache config
  file: path=/etc/apache2/sites-enabled/default state=absent
  notify: restart apache

- name: render apache sites available
  template: src=apache-wp.j2 dest=/etc/apache2/sites-available/{{site_name}}
  notify: restart apache

- name: Creating config link to sites available
  file: src=/etc/apache2/sites-available/{{site_name}} dest=/etc/nginx/sites-enabled/{{site_name}} state=link owner=root group=root
  notify: restart apache





