---
- name: create user group
  group: name=wp state=present

- name: add ubuntu to wp
  user: name=ubuntu append=yes groups="adm,wp"

- name: Create www-data user
  user: name={{wp_user}} append=yes groups="adm,wp" shell=/bin/bash

- name: upload sudoers.d file
  copy: src=sudoers-admin dest=/tmp/admin-sudo owner=root group=root mode=0440

- name: move file to sudoers.d
  shell: visudo -q -c -f /tmp/admin-sudo && cp /tmp/admin-sudo /etc/sudoers.d/admin-sudo

- name: install apt requirements
  apt: pkg={{item}} state=present update_cache=yes install_recommends=yes
  with_items:
    - mysql
    - php
    - php-mysql
    - apache2
    - python-mysqldb
  notify: restart apache

- name: setup mysql database
  mysql_db: db={{database_name}} state=present login_host={{database_host}} login_password={{database_root_password}} login_user={{database_root_user}}
  notify: restart apache

- name: setup mysql user
  mysql_user: mysql_user: name={{database_user}} password={{database_password}} priv={{database_name}}.*:ALL state=present login_host={{database_host}} login_password={{database_root_password}} login_user={{database_root_user}}
  notify: restart apache

- name: download wordpress
  get_url: url=http://wordpress.org/latest.tar.gz dest={{app_base_dir}}/{{wp_dir_name}}.tar.gz mode=0764

- name: untar wordpress
  command: tar -xzvf {{wp_dir_name}}.tar.gz creates={{app_base_dir}}/{{wp_dir_name}}/wp-created chdir = {{app_base_dir}}
  notify: restart apache

- name: render wp-config.php from template
  template: src=wp-config.php.j2 dest={{app_base_dir}}/{{wp_dir_name}}/wp-config.php owner=root group=root mode=0644
  notify: restart apache

- name: change ownership on wordpress directory to wp_user
  shell: chown -R {{wp_user}} {{app_base_dir}}/{{wp_dir_name}}

- name: create apache directory and set perms
  file: path=/etc/apache2/sites-available owner=root group=edx mode=2775 state=directory

- name: Removing default apache config
  file: path=/etc/apache2/sites-enabled/default state=absent
  notify: restart apache

- name: render apache sites available
  template: src=apache-wp.j2 dest=/etc/apache2/sites-available/{{wp_dir_name}}
  notify: restart apache

- name: Creating config link to sites available
  file: src=/etc/apache2/sites-available/{{wp_dir_name}} dest=/etc/nginx/sites-enabled/{{wp_dir_name}} state=link owner=root group=root
  notify: restart apache





